name: jusuancloud_flutter
description: 聚算云 - 跨平台WebView浏览器

publish_to: 'none'

version: 1.0.5+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
    - family: TechFont
      fonts:
        - asset: assets/fonts/TechFont-Regular.ttf